# Generated by Django 3.1.1 on 2020-09-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='User',
        ),
    ]
