# Generated by Django 3.1.1 on 2020-09-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200924_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Login',
        ),
    ]
