# Generated by Django 3.1.1 on 2020-09-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200924_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logins',
        ),
    ]
