# Generated by Django 3.1.1 on 2020-09-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200924_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logins',
            new_name='Login',
        ),
    ]
